"use client";

import { useAccount } from "@/components/account-context";
import { DiscordAvatar } from "@/components/actor-trace";
import { listGmCellsNormalized, saveGmCell, type GmCell } from "@/lib/gm-cells";
import { canReadMissions } from "@/lib/permissions";
import { CheckCircle2, CircleDot, Clock3, PencilLine, Route } from "lucide-react";
import { motion } from "framer-motion";
import { useEffect, useMemo, useState } from "react";

const STAGES = [
  ["IDEA", "Idée"], ["WRITING", "Écriture"], ["PREPARATION", "Préparation"], ["ACTIVE", "En cours"],
  ["FINALIZATION", "Finalisation"], ["COMPLETED", "Terminée"], ["PAUSED", "En pause"],
] as const;

export function StorylineProgressPanel() {
  const { account, grade } = useAccount();
  const [cells, setCells] = useState<GmCell[]>([]), [editing, setEditing] = useState<GmCell | null>(null), [saved, setSaved] = useState("");
  const refresh = () => setCells(listGmCellsNormalized());
  useEffect(() => { refresh(); window.addEventListener("refgm:staff-updated", refresh); window.addEventListener("storage", refresh); return () => { window.removeEventListener("refgm:staff-updated", refresh); window.removeEventListener("storage", refresh); }; }, []);
  const ownCellId = useMemo(() => cells.find((cell) => cell.members.some((member) => member.userId === account.userId))?.id, [cells, account.userId]);
  const canEdit = canReadMissions(grade);

  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing || !canEdit) return;
    const data = new FormData(event.currentTarget);
    saveGmCell({ ...editing, members: editing.members, groupName: editing.groupName, trameLabel: String(data.get("label") || ""), trameInfo: String(data.get("info") || ""), trameStatus: String(data.get("status") || ""), trameProgress: Number(data.get("progress") || 0), trameStage: String(data.get("stage") || "IDEA"), trameNextStep: String(data.get("nextStep") || ""), trameUpdatedBy: account.displayName, trameUpdatedAt: new Date().toISOString() }, { id: account.userId, name: account.displayName });
    setEditing(null); setSaved("Avancement mis à jour et synchronisé avec l'équipe."); refresh(); window.setTimeout(() => setSaved(""), 3500);
  }

  return <main className="lab-bg min-h-dvh p-6 text-white lg:p-10"><div className="mx-auto max-w-7xl space-y-7"><header className="relative overflow-hidden rounded-[2rem] border border-violet-300/15 bg-gradient-to-br from-violet-400/[0.09] via-white/[0.025] to-transparent p-6 shadow-[0_28px_90px_rgba(0,0,0,.24)] sm:p-8"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-violet-400/10 blur-[100px]"/><div className="relative"><p className="text-xs uppercase tracking-[.22em] text-violet-200/55">Pilotage des trames</p><h1 className="mt-3 text-4xl font-medium tracking-tight">Trames en cours</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/42">Visualise et mets à jour chaque histoire, sa prochaine étape et l’équipe GameMaster responsable depuis un seul endroit.</p><div className="mt-6 grid max-w-xl grid-cols-3 gap-2">{([['Trames',cells.length],['Actives',cells.filter((cell)=>!['COMPLETED','PAUSED'].includes(cell.trameStage||'')).length],['Terminées',cells.filter((cell)=>cell.trameStage==='COMPLETED').length]] as const).map(([label,value])=><div key={label} className="rounded-xl border border-white/[0.06] bg-black/15 px-3 py-3"><p className="text-xl font-medium text-white/85">{value}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-white/30">{label}</p></div>)}</div></div></header>
  {saved ? <motion.p initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border border-emerald-400/15 bg-emerald-400/[0.06] p-3 text-sm text-emerald-200">{saved}</motion.p> : null}
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cells.length ? cells.map((cell) => { const progress = cell.trameProgress ?? 0; const own = cell.id === ownCellId; const lead = cell.members.find((member) => member.cellRole === "PRINCIPAL"); return <motion.article layout key={cell.id} className={`rounded-3xl border p-5 ${own ? "border-violet-400/25 bg-violet-400/[0.045]" : "border-white/[0.08] bg-white/[0.025]"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.18em] text-white/30">{cell.groupName}</p><h2 className="mt-2 text-xl font-medium">{cell.trameLabel || "Trame à définir"}</h2></div><span className="rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[10px] text-white/50">{STAGES.find(([id]) => id === cell.trameStage)?.[1] || "Idée"}</span></div><div className="mt-5"><div className="mb-2 flex items-center justify-between text-xs"><span className="text-white/40">Avancement global</span><b className="text-violet-200">{progress}%</b></div><div className="h-2 overflow-hidden rounded-full bg-white/[0.07]"><motion.div initial={{ width: 0 }} animate={{ width: `${progress}%` }} className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-200" /></div></div><p className="mt-5 min-h-12 whitespace-pre-wrap text-sm leading-6 text-white/50">{cell.trameInfo || "Aucun résumé ajouté pour le moment."}</p><div className="mt-4 space-y-2 rounded-xl border border-white/[0.06] bg-black/15 p-3 text-xs text-white/45"><p className="flex gap-2"><CircleDot className="h-4 w-4 shrink-0 text-violet-200/60"/><span><b className="text-white/60">État :</b> {cell.trameStatus || "Non renseigné"}</span></p><p className="flex gap-2"><Route className="h-4 w-4 shrink-0 text-violet-200/60"/><span><b className="text-white/60">Prochaine étape :</b> {cell.trameNextStep || "À définir"}</span></p></div><div className="mt-4 flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2">{lead ? <DiscordAvatar name={lead.displayName} size={26} className="rounded-lg"/> : null}<span className="truncate text-[11px] text-white/30">{cell.trameUpdatedAt ? `Mis à jour par ${cell.trameUpdatedBy || "un GM"} · ${new Date(cell.trameUpdatedAt).toLocaleDateString("fr-FR")}` : "Aucune mise à jour"}</span></div>{canEdit ? <button onClick={() => setEditing(cell)} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-violet-400/20 px-2.5 py-2 text-xs text-violet-100/70 hover:bg-violet-400/10"><PencilLine className="h-3.5 w-3.5"/>Mettre à jour</button> : null}</div></motion.article>; }) : <div className="col-span-full rounded-3xl border border-dashed border-white/10 p-12 text-center"><Clock3 className="mx-auto h-7 w-7 text-white/25"/><p className="mt-3 text-sm text-white/40">Aucune équipe GameMaster n'a encore été configurée.</p></div>}</section>
  {editing ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditing(null); }}><motion.form initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-white/10 bg-[#111114] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-violet-200/45">{editing.groupName}</p><h2 className="mt-1 text-2xl font-medium">Mettre à jour la trame</h2></div><button type="button" onClick={() => setEditing(null)} className="text-sm text-white/40">Fermer</button></div><div className="mt-6 grid gap-4"><label className="text-sm text-white/55">Nom de la trame<input name="label" defaultValue={editing.trameLabel} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-white outline-none"/></label><label className="text-sm text-white/55">Résumé<textarea name="info" rows={5} defaultValue={editing.trameInfo} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-white outline-none"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-white/55">Étape actuelle<select name="stage" defaultValue={editing.trameStage || "IDEA"} className="mt-2 w-full rounded-xl border border-white/10 bg-[#161619] p-3 text-white">{STAGES.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="text-sm text-white/55">Pourcentage<input name="progress" type="number" min="0" max="100" defaultValue={editing.trameProgress ?? 0} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-white outline-none"/></label></div><label className="text-sm text-white/55">État actuel<input name="status" defaultValue={editing.trameStatus} placeholder="Ex. repérages terminés" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-white outline-none"/></label><label className="text-sm text-white/55">Prochaine étape<textarea name="nextStep" rows={3} defaultValue={editing.trameNextStep} placeholder="Ce qu'il reste à préparer…" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-white outline-none"/></label></div><button className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-300 px-4 py-3 font-medium text-[#071014]"><CheckCircle2 className="h-4 w-4"/>Enregistrer l'avancement</button></motion.form></div> : null}</div></main>;
}
