"use client";

import { DiscordAvatar } from "@/components/actor-trace";
import { RECRUITMENT_STATUS_LABEL, type RecruitmentStatus, type VoiceSlot } from "@/lib/recruitment";
import { BriefcaseBusiness, CalendarCheck2, Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, ExternalLink, FileText, Lightbulb, LockKeyhole, PartyPopper, RotateCcw, ShieldCheck, UserRound } from "lucide-react";
import { motion } from "framer-motion";
import { cloneElement, useEffect, useRef, useState, type FormEvent, type ReactElement } from "react";
import type React from "react";
import { readApiResponse } from "@/lib/api-response";

type Row = { user_id?: string; first_name?: string; age?: number; unique_id?: string; experience?: string; motivation?: string; availability?: string; integration_availability?: string; document_url?: string; trame_summary?: string; discord_name?: string; discord_avatar_url?: string; personal_introduction?: string; legal_rp_experience?: string; illegal_rp_experience?: string; servers_visited?: string; rp_storylines?: string; gm_missions?: string; rp_events?: string; suggestions?: string; why_gm?: string; qualities?: string; long_term_contribution?: string; staff_experience?: string; additional_information?: string; status: RecruitmentStatus; candidate_message?: string | null; voice_slots?: VoiceSlot[]; selected_voice_slot_id?: string | null; updated_at?: string };
type Settings = { open: boolean; message: string };
const STEPS = ["Présentation", "Expériences RP", "Vos idées", "Pourquoi toi ?", "Compléments", "Trame"];
const DAYS = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"];

export function CandidateApplicationPanel({ discordName, discordAvatarUrl, discordId }: { discordName: string; discordAvatarUrl?: string | null; discordId: string }) {
  const [app, setApp] = useState<Row | null>(null), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  const [error, setError] = useState(""), [step, setStep] = useState(0);
  const [settings, setSettings] = useState<Settings>({ open: true, message: "" }), [savedMessage, setSavedMessage] = useState("");
  const formRef = useRef<HTMLFormElement>(null);
  const editable = !app || app.status === "DRAFT" || app.status === "MORE_INFO";
  const waiting = Boolean(app && ["SUBMITTED", "ANALYZING", "STAFF_REVIEW", "DECISION_PENDING"].includes(app.status));
  const avatar = app?.discord_avatar_url || discordAvatarUrl;
  const name = app?.discord_name || discordName;
  const applicationStatus = app?.status;

  useEffect(() => {
    let active = true;
    async function refresh(silent = false) {
      try {
        const response = await fetch("/api/recruitment/application", { cache: "no-store" });
        const result = await readApiResponse<{ application: Row | null; settings: Settings; error: string }>(response);
        if (!response.ok) throw new Error(result.error || "Impossible de charger ta candidature.");
        if (!active) return;
        const nextApplication = result.application ?? null;
        setApp((current) => JSON.stringify(current) === JSON.stringify(nextApplication) ? current : nextApplication);
        if (result.settings) setSettings(result.settings);
        if (!silent) setError("");
      } catch (cause) {
        if (active && !silent) setError(cause instanceof Error ? cause.message : "Impossible de charger ta candidature.");
      } finally {
        if (active) setLoading(false);
      }
    }
    void refresh();
    // Une actualisation fréquente reste réactive sans marteler Supabase.
    const timer = window.setInterval(() => { if (document.visibilityState === "visible" && (!applicationStatus || !["ACCEPTED", "REJECTED", "CLOSED"].includes(applicationStatus))) void refresh(true); }, 60000);
    const refreshWhenVisible = () => { if (document.visibilityState === "visible") void refresh(true); };
    window.addEventListener("focus", refreshWhenVisible);
    document.addEventListener("visibilitychange", refreshWhenVisible);
    return () => { active = false; window.clearInterval(timer); window.removeEventListener("focus", refreshWhenVisible); document.removeEventListener("visibilitychange", refreshWhenVisible); };
  }, [applicationStatus]);

  function formData() { return formRef.current ? Object.fromEntries(new FormData(formRef.current)) : null; }
  function goToStep(next: number) { if (next <= step) { setError(""); setStep(next); return; } for (let index = 0; index < next; index += 1) if (!validate(index)) return; setSavedMessage(""); setStep(next); }
  function validate(targetStep: number, submit = false) {
    const data = formData(); if (!data) return false;
    const firstName = String(data.firstName || "").trim(), age = Number(data.age), uniqueId = String(data.uniqueId || "").trim();
    const personalIntroduction = String(data.personalIntroduction || "").trim(), legalRpExperience = String(data.legalRpExperience || "").trim(), illegalRpExperience = String(data.illegalRpExperience || "").trim();
    const rpStorylines = String(data.rpStorylines || "").trim(), gmMissions = String(data.gmMissions || "").trim(), rpEvents = String(data.rpEvents || "").trim(), suggestions = String(data.suggestions || "").trim();
    const whyGm = String(data.whyGm || "").trim(), qualities = String(data.qualities || "").trim(), longTermContribution = String(data.longTermContribution || "").trim(), availability = String(data.availability || "").trim();
    const documentUrl = String(data.documentUrl || "").trim();
    if (targetStep === 0 && (!firstName || !uniqueId || !Number.isFinite(age) || age < 13 || age > 99)) { setStep(0); setError("Renseigne ton prénom, un âge valide et ton ID unique."); return false; }
    if (targetStep === 0 && personalIntroduction.length < 80) { setStep(0); setError("Présente-toi en au moins 80 caractères : parcours RP, personnalité et sérieux."); return false; }
    if (targetStep === 1 && (legalRpExperience.length < 20 || illegalRpExperience.length < 20)) { setStep(1); setError("Réponds aux deux expériences RP en au moins 20 caractères, même si tu n’en as pas encore."); return false; }
    if (targetStep === 2 && [rpStorylines, gmMissions, rpEvents, suggestions].some((value) => value.length < 40)) { setStep(2); setError("Développe chacune de tes idées en au moins 40 caractères."); return false; }
    if (targetStep === 3 && [whyGm, qualities, longTermContribution].some((value) => value.length < 60)) { setStep(3); setError("Développe chaque réponse de cette section en au moins 60 caractères."); return false; }
    if (targetStep === 4 && availability) { const invalid = availability.split("\n").some((line) => { const match = line.match(/:\s*(\d\d:\d\d)-(\d\d:\d\d)$/); return !match || match[1] >= match[2]; }); if (invalid) { setStep(4); setError("Pour chaque disponibilité, l’heure de fin doit être après l’heure de début."); return false; } }
    if (targetStep === 5) { let validUrl = false; try { const url = new URL(documentUrl); validUrl = /(^|\.)(canva\.com|docs\.google\.com|drive\.google\.com)$/i.test(url.hostname) || /\.pdf($|[?#])/i.test(url.pathname + url.search); } catch {} if (!validUrl) { setStep(5); setError("Ajoute un lien Canva, Google Docs/Drive ou PDF valide et accessible."); return false; } }
    if (submit) for (let index = 0; index < STEPS.length; index += 1) if (!validate(index)) return false;
    setError(""); return true;
  }

  async function save(submit: boolean) {
    const form = formRef.current;
    if (!form || saving) return;
    const data = Object.fromEntries(new FormData(form));
    if (submit && (!settings.open || !validate(0, true))) { if (!settings.open) setError(settings.message); return; }
    setSaving(true); setError("");
    const response = await fetch("/api/recruitment/application", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...data, age: Number(data.age), submit }) });
    const result = await readApiResponse<{ application: Row; error: string }>(response); setSaving(false);
    if (!response.ok) return setError(result.error || "Une erreur est survenue.");
    if (!result.application) return setError("La candidature n’a pas été renvoyée par le serveur.");
    setApp(result.application); setSavedMessage(submit ? "" : "Brouillon sauvegardé."); if (submit) setStep(0);
  }

  async function chooseSlot(id: string) {
    setSaving(true); setError("");
    const response = await fetch("/api/recruitment/application", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ selectedVoiceSlotId: id }) });
    const result = await readApiResponse<{ application: Row; error: string }>(response); setSaving(false);
    if (!response.ok) return setError(result.error || "Impossible de choisir ce créneau.");
    if (result.application) setApp(result.application);
  }

  async function sendIntegrationAvailability(value: string) {
    if (!value || saving) return;
    setSaving(true); setError("");
    const response = await fetch("/api/recruitment/application", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ integrationAvailability: value }) });
    const result = await readApiResponse<{ application: Row; error: string }>(response); setSaving(false);
    if (!response.ok) return setError(result.error || "Impossible d’enregistrer tes disponibilités.");
    if (result.application) setApp(result.application);
  }

  async function restartApplication() {
    if (saving || !settings.open) return;
    setSaving(true); setError("");
    const response = await fetch("/api/recruitment/application", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ restart: true }) });
    const result = await readApiResponse<{ application: Row; error: string }>(response); setSaving(false);
    if (!response.ok) return setError(result.error || "Impossible de recommencer ta candidature.");
    if (!result.application) return setError("La nouvelle candidature n’a pas été renvoyée par le serveur.");
    setApp(result.application); setStep(0); setSavedMessage("Nouvelle candidature créée. Ton ancien dossier reste conservé par l'équipe.");
  }

  if (loading) return <CandidateFormSkeleton />;
  if (app?.status === "CLOSED") return <ClosedApplication app={app} name={name} avatar={avatar} settings={settings} saving={saving} error={error} onRestart={restartApplication} />;
  if (!editable && app) return <SubmittedView app={app} name={name} avatar={avatar} waiting={waiting} saving={saving} error={error} chooseSlot={chooseSlot} sendIntegrationAvailability={sendIntegrationAvailability} />;
  if (!settings.open && (!app || app.status === "DRAFT")) return <ClosedRecruitment name={name} avatar={avatar} message={settings.message} />;

  return <section className="mx-auto max-w-4xl overflow-hidden rounded-[1.75rem] border border-white/[0.08] bg-[#0d0d0f]/90 shadow-[0_30px_100px_-55px_rgba(56,189,248,.35)]">
    <header className="border-b border-white/[0.07] px-5 py-6 sm:px-8"><div className="flex items-center gap-4"><DiscordAvatar name={name} url={avatar} size={54} className="rounded-2xl border-violet-300/20" /><div className="min-w-0"><p className="text-[11px] tracking-[.2em] text-violet-200/55 uppercase">Candidature GameMaster</p><h1 className="mt-1 truncate text-xl font-medium tracking-tight sm:text-2xl">Bienvenue, {name}</h1><p className="mt-1 text-sm text-white/40">Six étapes claires, modifiables jusqu’à l’envoi.</p></div></div>
      <nav className="mt-7 grid grid-cols-3 gap-2 sm:grid-cols-6" aria-label="Avancement de la candidature">{STEPS.map((label, index) => <button key={label} type="button" aria-current={index === step ? "step" : undefined} onClick={() => goToStep(index)} className="text-left"><span className={`mb-2 block h-1 rounded-full transition-colors ${index < step ? "bg-violet-300/45" : index === step ? "bg-violet-300" : "bg-white/[0.08]"}`} /><span className={`block truncate text-[9px] sm:text-[10px] ${index === step ? "text-white/80" : index < step ? "text-white/45" : "text-white/25"}`}><span className="hidden lg:inline">{index + 1}. </span>{label}</span></button>)}</nav>
    </header>
    <form ref={formRef} className="p-5 sm:p-8" onSubmit={(event) => event.preventDefault()}>
        <div className="min-h-[460px]">
          <StepPanel active={step === 0} icon={<UserRound />} title="Présentation" hint="Présente-toi clairement pour que l’équipe puisse apprendre à te connaître."><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_130px]"><Field label="ID Discord"><input value={app?.user_id || discordId} readOnly disabled className="opacity-60" /></Field><Field label="ID unique"><input name="uniqueId" defaultValue={app?.unique_id} placeholder="Ton ID unique en jeu" /></Field><Field label="Âge"><input name="age" type="number" min="13" max="99" defaultValue={app?.age} placeholder="18" /></Field></div><Field label="Prénom"><input name="firstName" defaultValue={app?.first_name} placeholder="Ton prénom" /></Field><Field label="Présentation personnelle · 80 caractères minimum"><textarea name="personalIntroduction" rows={9} defaultValue={app?.personal_introduction} placeholder="Présente-toi IRL, ton parcours RP, ta personnalité, ton sérieux…" /></Field></div></StepPanel>
          <StepPanel active={step === 1} icon={<BriefcaseBusiness />} title="Expériences RP" hint="Explique séparément ton expérience dans le légal et l’illégal."><div className="grid gap-5 lg:grid-cols-2"><Field label="Expérience RP légale"><textarea name="legalRpExperience" rows={8} defaultValue={app?.legal_rp_experience || app?.experience} placeholder="Police, EMS, gouvernement, entreprises… Si tu n’en as pas, explique-le." /></Field><Field label="Expérience RP illégale"><textarea name="illegalRpExperience" rows={8} defaultValue={app?.illegal_rp_experience} placeholder="Gangs, organisations, trames criminelles… Si tu n’en as pas, explique-le." /></Field><div className="lg:col-span-2"><Field label="Serveurs fréquentés · optionnel"><textarea name="serversVisited" rows={4} defaultValue={app?.servers_visited} placeholder="Noms des serveurs et rôles joués, si applicable." /></Field></div></div></StepPanel>
          <StepPanel active={step === 2} icon={<Lightbulb />} title="Vos idées" hint="Donne des exemples concrets et originaux adaptés au serveur."><div className="grid gap-5 lg:grid-cols-2"><Field label="Trames RP"><textarea name="rpStorylines" rows={7} defaultValue={app?.rp_storylines} placeholder="Quelles trames aimerais-tu construire ?" /></Field><Field label="Missions GM"><textarea name="gmMissions" rows={7} defaultValue={app?.gm_missions} placeholder="Quels types de missions proposerais-tu ?" /></Field><Field label="Événements RP"><textarea name="rpEvents" rows={7} defaultValue={app?.rp_events} placeholder="Quels événements pourrais-tu organiser ?" /></Field><Field label="Suggestions"><textarea name="suggestions" rows={7} defaultValue={app?.suggestions} placeholder="Immersion, équilibre légal/illégal, activité et originalité…" /></Field></div></StepPanel>
          <StepPanel active={step === 3} icon={<ShieldCheck />} title="Pourquoi toi ?" hint="Explique ta motivation et ce que tu apporterais réellement à l’équipe."><div className="space-y-5"><Field label="Pourquoi souhaites-tu devenir GM ?"><textarea name="whyGm" rows={7} defaultValue={app?.why_gm || app?.motivation} placeholder="Tes motivations et ta vision du rôle de GameMaster…" /></Field><div className="grid gap-5 lg:grid-cols-2"><Field label="Tes qualités"><textarea name="qualities" rows={7} defaultValue={app?.qualities} placeholder="Impartialité, créativité, disponibilité, gestion RP…" /></Field><Field label="Ce que tu peux apporter sur le long terme"><textarea name="longTermContribution" rows={7} defaultValue={app?.long_term_contribution} placeholder="Ton implication future, tes projets et ta régularité…" /></Field></div></div></StepPanel>
          <StepPanel active={step === 4} icon={<Clock3 />} title="Informations complémentaires" hint="Cette partie est optionnelle, mais elle peut aider l’équipe à mieux organiser la suite."><div className="space-y-5"><div><p className="mb-3 text-sm text-white/55">Disponibilités · optionnel</p><AvailabilityPicker initialValue={app?.availability || ""} /></div><div className="grid gap-5 lg:grid-cols-2"><Field label="Expérience staff · optionnel"><textarea name="staffExperience" rows={6} defaultValue={app?.staff_experience} placeholder="Si oui, précise le rôle, le serveur et la durée." /></Field><Field label="Autres informations utiles · optionnel"><textarea name="additionalInformation" rows={6} defaultValue={app?.additional_information} placeholder="Tout élément supplémentaire que tu souhaites transmettre." /></Field></div></div></StepPanel>
          <StepPanel active={step === 5} icon={<FileText />} title="Analyse de ta trame" hint="Transmets un document accessible afin que le site et les référents puissent étudier ta trame."><div className="space-y-5"><Field label="Lien Canva, Google Docs/Drive ou fichier PDF"><input name="documentUrl" type="url" defaultValue={app?.document_url} placeholder="https://…" /></Field><div className="rounded-xl border border-violet-400/15 bg-violet-400/[0.05] p-4 text-sm leading-6 text-violet-100/55"><p className="font-medium text-violet-100/80">Avant d’envoyer</p><p className="mt-1">Vérifie que le lien est accessible aux personnes disposant du lien. Un Google Docs public peut être lu automatiquement. Pour Canva, Drive ou PDF, les référents ouvriront le dossier et l’avis automatique s’appuiera sur tes réponses écrites.</p></div></div></StepPanel>
        </div>
      {error && <p role="alert" className="mb-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{savedMessage && !error ? <p className="mb-4 rounded-xl border border-emerald-400/15 bg-emerald-400/[0.06] p-3 text-sm text-emerald-200">{savedMessage}</p> : null}
      <div className="flex flex-col-reverse gap-3 border-t border-white/[0.07] pt-5 sm:flex-row sm:items-center sm:justify-between"><button type="button" disabled={step === 0} onClick={() => { setError(""); setSavedMessage(""); setStep((v) => v - 1); }} className="inline-flex items-center justify-center gap-2 rounded-xl px-3 py-2.5 text-sm text-white/50 disabled:invisible"><ChevronLeft className="h-4 w-4" />Retour</button><div className="grid grid-cols-2 gap-2 sm:flex"><button type="button" disabled={saving} onClick={() => void save(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-white/60 hover:bg-white/5">{saving ? "Sauvegarde…" : "Sauvegarder"}</button>{step < STEPS.length - 1 ? <button type="button" onClick={() => { setSavedMessage(""); if (validate(step)) setStep((v) => v + 1); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-medium text-black">Continuer<ChevronRight className="h-4 w-4" /></button> : <button disabled={saving} type="button" onClick={() => void save(true)} className="rounded-xl bg-violet-300 px-4 py-2.5 text-sm font-medium text-[#071014] hover:bg-violet-200 disabled:opacity-60">{saving ? "Envoi en cours…" : "Envoyer ma candidature"}</button>}</div></div>
    </form>
  </section>;
}

function StepPanel({ active, icon, title, hint, children }: { active: boolean; icon: ReactElement; title: string; hint: string; children: React.ReactNode }) { return <section className={active ? "block" : "hidden"}><div className="mb-7 flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-violet-400/15 bg-violet-400/[0.07] text-violet-200 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><div><h2 className="text-lg font-medium">{title}</h2><p className="mt-1 text-sm text-white/40">{hint}</p></div></div>{children}</section>; }

function AvailabilityPicker({ initialValue, name = "availability" }: { initialValue: string; name?: string }) {
  const parsed = Object.fromEntries(initialValue.split("\n").map((line) => { const match = line.match(/^([^:]+):\s*(\d\d:\d\d)-(\d\d:\d\d)$/); return match ? [match[1], { enabled: true, start: match[2], end: match[3] }] : []; }).filter((v) => v.length));
  const [slots, setSlots] = useState<Record<string, { enabled: boolean; start: string; end: string }>>(() => Object.fromEntries(DAYS.map((day) => [day, parsed[day] || { enabled: false, start: "18:00", end: "22:00" }])));
  const value = DAYS.filter((day) => slots[day].enabled).map((day) => `${day}: ${slots[day].start}-${slots[day].end}`).join("\n");
  return <div className="space-y-2"><input type="hidden" name={name} value={value} />{DAYS.map((day) => { const slot = slots[day]; return <div key={day} className={`grid items-center gap-3 rounded-xl border p-3 transition-colors sm:grid-cols-[120px_1fr] ${slot.enabled ? "border-violet-400/20 bg-violet-400/[0.05]" : "border-white/[0.07] bg-black/15"}`}><button type="button" onClick={() => setSlots((all) => ({ ...all, [day]: { ...slot, enabled: !slot.enabled } }))} className="flex items-center gap-3 text-left text-sm"><span className={`flex h-5 w-5 items-center justify-center rounded-md border ${slot.enabled ? "border-violet-300/50 bg-violet-300 text-black" : "border-white/15"}`}>{slot.enabled && <Check className="h-3 w-3" />}</span>{day}</button><div className={`flex items-center gap-2 transition-opacity ${slot.enabled ? "opacity-100" : "pointer-events-none opacity-25"}`}><input aria-label={`Début ${day}`} type="time" value={slot.start} onChange={(e) => setSlots((all) => ({ ...all, [day]: { ...slot, start: e.target.value } }))} className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-sm" /><span className="text-xs text-white/30">à</span><input aria-label={`Fin ${day}`} type="time" value={slot.end} onChange={(e) => setSlots((all) => ({ ...all, [day]: { ...slot, end: e.target.value } }))} className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-sm" /></div></div>; })}</div>;
}

function SubmittedView({ app, name, avatar, waiting, saving, error, chooseSlot, sendIntegrationAvailability }: { app: Row; name: string; avatar?: string | null; waiting: boolean; saving: boolean; error: string; chooseSlot: (id: string) => void; sendIntegrationAvailability: (value: string) => void }) {
  return <div className="mx-auto max-w-3xl space-y-5">
    <StatusCard app={app} name={name} avatar={avatar} waiting={waiting} />
    {app.status === "VOICE_PROPOSED" ? <VoiceChoice app={app} saving={saving} chooseSlot={chooseSlot} /> : null}
    {app.status === "ACCEPTED" ? <IntegrationCard app={app} saving={saving} error={error} onSend={sendIntegrationAvailability} /> : null}
    <section className="rounded-2xl border border-white/[0.08] bg-white/[0.02] p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-white/85">Ton dossier de candidature</p><p className="mt-1 text-xs text-white/35">Retrouve ta trame et toutes les informations envoyées.</p></div>{app.document_url ? <a href={app.document_url} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-sm text-white/65 hover:bg-white/5">Ouvrir la trame <ExternalLink className="h-4 w-4" /></a> : null}</div><div className="mt-5 space-y-6"><DetailGroup title="Présentation"><CandidateDetail title="Présentation personnelle" value={app.personal_introduction} /></DetailGroup><DetailGroup title="Expériences RP"><CandidateDetail title="Expérience légale" value={app.legal_rp_experience || app.experience} /><CandidateDetail title="Expérience illégale" value={app.illegal_rp_experience} /><CandidateDetail title="Serveurs fréquentés" value={app.servers_visited} /></DetailGroup><DetailGroup title="Vos idées"><CandidateDetail title="Trames RP" value={app.rp_storylines || app.trame_summary} /><CandidateDetail title="Missions GM" value={app.gm_missions} /><CandidateDetail title="Événements RP" value={app.rp_events} /><CandidateDetail title="Suggestions" value={app.suggestions} /></DetailGroup><DetailGroup title="Pourquoi toi ?"><CandidateDetail title="Pourquoi devenir GM" value={app.why_gm || app.motivation} /><CandidateDetail title="Qualités" value={app.qualities} /><CandidateDetail title="Apport à long terme" value={app.long_term_contribution} /></DetailGroup><DetailGroup title="Informations complémentaires"><CandidateDetail title="Disponibilités" value={app.availability} /><CandidateDetail title="Expérience staff" value={app.staff_experience} /><CandidateDetail title="Autres informations" value={app.additional_information} /></DetailGroup></div></section>
  </div>;
}

function StatusCard({ app, name, avatar, waiting }: { app: Row; name: string; avatar?: string | null; waiting: boolean }) { const accepted = app.status === "ACCEPTED"; const closed = app.status === "CLOSED"; return <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className={`relative overflow-hidden rounded-[1.75rem] border p-7 sm:p-9 ${accepted ? "border-emerald-400/25 bg-emerald-400/[0.06]" : closed ? "border-white/10 bg-white/[0.02]" : "border-white/[0.08] bg-gradient-to-br from-white/[0.06] via-white/[0.02] to-transparent"}`}><motion.div className={`absolute -top-16 -right-16 h-44 w-44 rounded-full blur-3xl ${accepted ? "bg-emerald-400/20" : "bg-violet-400/10"}`} animate={{ scale: [1, 1.15, 1], opacity: [.45, .8, .45] }} transition={{ duration: 3.2, repeat: Infinity }} /><div className="relative flex items-center gap-4"><DiscordAvatar name={name} url={avatar} size={60} className="rounded-2xl border-violet-300/20" /><div><p className="text-xs tracking-[.2em] text-white/35 uppercase">Candidature de {name}</p><h1 className="mt-1 text-2xl font-medium">{RECRUITMENT_STATUS_LABEL[app.status]}</h1></div>{accepted ? <motion.div className="ml-auto hidden text-emerald-300 sm:block" animate={{ rotate: [-5, 7, -5] }} transition={{ duration: 2.2, repeat: Infinity }}><PartyPopper className="h-9 w-9" /></motion.div> : null}</div>{accepted ? <p className="relative mt-7 text-base leading-7 text-emerald-50/80">Félicitations, ta candidature est acceptée ! Il ne reste plus qu’à préparer ton intégration et ton start en tant que GameMaster.</p> : waiting ? <WaitingCard status={app.status} /> : <p className="relative mt-7 text-sm text-white/50"><CheckCircle2 className="mr-2 inline h-4 w-4" />{closed ? "Cette candidature est maintenant terminée." : "Ta candidature a bien été mise à jour."}</p>}{app.candidate_message ? <p className="relative mt-5 rounded-xl border border-white/[0.07] bg-black/15 p-4 text-sm leading-6 text-white/65">{app.candidate_message}</p> : null}</motion.section>; }

function VoiceChoice({ app, saving, chooseSlot }: { app: Row; saving: boolean; chooseSlot: (id: string) => void }) { return <motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="rounded-2xl border border-violet-400/20 bg-violet-400/[0.06] p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-violet-300/10 p-2 text-violet-200"><Clock3 className="h-5 w-5" /></span><div><h2 className="font-medium">Choisis ton entretien vocal</h2><p className="text-xs text-white/40">Sélectionne simplement le créneau qui te convient.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{(app.voice_slots || []).map((slot) => <button key={slot.id} disabled={saving} onClick={() => chooseSlot(slot.id)} className={`rounded-xl border p-3 text-left text-sm transition-colors ${app.selected_voice_slot_id === slot.id ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-100" : "border-white/10 bg-black/15 hover:bg-white/5"}`}><Clock3 className="mr-2 inline h-4 w-4" />{new Date(slot.startsAt).toLocaleString("fr-FR")}</button>)}</div></motion.section>; }

function IntegrationCard({ app, saving, error, onSend }: { app: Row; saving: boolean; error: string; onSend: (value: string) => void }) { const formRef = useRef<HTMLFormElement>(null); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const value = String(new FormData(event.currentTarget).get("integrationAvailability") || ""); onSend(value); } return <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .12 }} className="rounded-2xl border border-emerald-400/20 bg-emerald-400/[0.04] p-5 sm:p-6"><div className="flex items-start gap-3"><CalendarCheck2 className="mt-0.5 h-5 w-5 text-emerald-300" /><div><h2 className="font-medium text-white/90">Préparons ton intégration</h2><p className="mt-1 text-sm leading-6 text-white/45">Merci de nous redonner tes disponibilités actuelles pour organiser ton intégration et ton premier start.</p></div></div>{app.integration_availability ? <div className="mt-5 rounded-xl border border-emerald-400/15 bg-black/15 p-4"><p className="text-xs uppercase tracking-wider text-emerald-200/50">Disponibilités transmises</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/70">{app.integration_availability}</p></div> : <form ref={formRef} onSubmit={submit} className="mt-5"><AvailabilityPicker name="integrationAvailability" initialValue="" />{error ? <p className="mt-3 text-sm text-rose-200">{error}</p> : null}<button disabled={saving} className="mt-4 w-full rounded-xl bg-emerald-300 px-4 py-3 text-sm font-medium text-[#07120d] disabled:opacity-50">{saving ? "Enregistrement…" : "Transmettre mes disponibilités"}</button></form>}</motion.section>; }

function CandidateDetail({ title, value }: { title: string; value?: string }) { return <div className="min-w-0 overflow-hidden rounded-xl border border-white/[0.06] bg-black/15 p-4"><p className="text-[10px] uppercase tracking-wider text-white/30">{title}</p><p className="mt-2 min-w-0 whitespace-pre-wrap break-words text-sm leading-6 text-white/60 [overflow-wrap:anywhere]">{value || "Non renseigné"}</p></div>; }
function DetailGroup({ title, children }: { title: string; children: React.ReactNode }) { return <div><p className="mb-3 text-xs font-medium uppercase tracking-[.16em] text-violet-200/45">{title}</p><div className="grid gap-3 sm:grid-cols-2">{children}</div></div>; }

function WaitingCard({ status }: { status: RecruitmentStatus }) { const labels = ["Candidature reçue", "Analyse", "Étude référents", "Décision"]; const active = status === "SUBMITTED" ? 0 : status === "ANALYZING" ? 1 : status === "STAFF_REVIEW" ? 2 : 3; return <div className="mt-8"><div className="grid grid-cols-4 gap-2">{labels.map((label, index) => <div key={label}><div className={`h-1 rounded-full ${index <= active ? "bg-violet-300/70" : "bg-white/[0.08]"}`}>{index === active && <motion.div className="h-full rounded-full bg-white" animate={{ opacity: [.25, 1, .25] }} transition={{ duration: 1.4, repeat: Infinity }} />}</div><p className={`mt-2 text-[10px] sm:text-xs ${index <= active ? "text-white/60" : "text-white/25"}`}>{label}</p></div>)}</div><p className="mt-6 flex items-center gap-2 text-sm text-white/45"><Clock3 className="h-4 w-4 text-violet-200" />Tu peux revenir ici à tout moment pour suivre l’avancement.</p></div>; }

function Field({ label, children }: { label: string; children: ReactElement<{ className?: string; disabled?: boolean }> }) { return <label className="block space-y-2 text-sm text-white/55"><span>{label}</span>{cloneElement(children, { className: `w-full rounded-xl border border-white/10 bg-black/35 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/25 focus:border-violet-400/40 ${children.props.className || ""}` })}</label>; }

function CandidateFormSkeleton() { return <section className="mx-auto max-w-4xl animate-pulse overflow-hidden rounded-[1.75rem] border border-white/[0.08] bg-white/[0.02]" aria-busy="true" aria-label="Chargement de la candidature"><div className="border-b border-white/[0.07] p-6 sm:p-8"><div className="flex items-center gap-4"><div className="h-14 w-14 rounded-2xl bg-white/[0.08]" /><div className="space-y-2"><div className="h-3 w-36 rounded bg-white/[0.05]" /><div className="h-7 w-52 rounded-lg bg-white/[0.09]" /><div className="h-3 w-64 max-w-full rounded bg-white/[0.05]" /></div></div><div className="mt-7 grid grid-cols-3 gap-2 sm:grid-cols-6">{STEPS.map((label) => <div key={label} className="h-1 rounded-full bg-white/[0.07]" />)}</div></div><div className="space-y-6 p-6 sm:p-8"><div className="h-10 w-48 rounded-xl bg-white/[0.07]" /><div className="grid gap-4 sm:grid-cols-3">{[0, 1, 2].map((item) => <div key={item} className="h-20 rounded-xl bg-white/[0.04]" />)}</div><div className="ml-auto h-10 w-32 rounded-xl bg-white/[0.08]" /></div></section>; }

function ClosedRecruitment({ name, avatar, message }: { name: string; avatar?: string | null; message: string }) { return <div className="flex min-h-[calc(100dvh-3rem)] w-full items-center justify-center py-8"><motion.section initial={{ opacity: 0, y: 16, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .45, ease: [.16, 1, .3, 1] }} className="relative w-full max-w-lg overflow-hidden rounded-[1.75rem] border border-white/[0.09] bg-[#0f0f12]/92 p-8 text-center shadow-[0_30px_100px_-45px_rgba(0,0,0,.9)] sm:p-10"><motion.div className="pointer-events-none absolute -top-24 left-1/2 h-48 w-48 -translate-x-1/2 rounded-full bg-white/[0.045] blur-3xl" animate={{ opacity: [.35,.7,.35], scale: [1,1.12,1] }} transition={{ duration: 4, repeat: Infinity }}/><div className="relative"><DiscordAvatar name={name} url={avatar} size={58} className="mx-auto rounded-2xl border-white/10"/><span className="mx-auto mt-6 flex h-11 w-11 items-center justify-center rounded-xl border border-white/[0.08] bg-white/[0.04] text-white/45"><LockKeyhole className="h-5 w-5"/></span><h1 className="mt-5 text-2xl font-medium tracking-tight text-white/90">Recrutements fermés</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-white/45">{message}</p><div className="mx-auto mt-6 h-px max-w-48 bg-gradient-to-r from-transparent via-white/10 to-transparent"/><p className="mt-5 text-xs leading-5 text-white/25">Ton compte Discord reste connecté. Reviens ici lors de la prochaine ouverture.</p></div></motion.section></div>; }

function ClosedApplication({ app, name, avatar, settings, saving, error, onRestart }: { app: Row; name: string; avatar?: string | null; settings: Settings; saving: boolean; error: string; onRestart: () => void }) {
  return <div className="mx-auto max-w-3xl space-y-5"><StatusCard app={app} name={name} avatar={avatar} waiting={false} /><motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="rounded-2xl border border-violet-400/15 bg-violet-400/[0.04] p-6 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-300/10 text-violet-200"><RotateCcw className="h-5 w-5" /></span><h2 className="mt-4 text-xl font-medium">Tu souhaites retenter ta chance ?</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-white/45">Tu peux créer une nouvelle candidature. L'ancien dossier et la décision précédente resteront conservés pour assurer le suivi du recrutement.</p>{!settings.open ? <p className="mt-4 rounded-xl border border-amber-400/15 bg-amber-400/[0.05] p-3 text-sm text-amber-100/65">{settings.message}</p> : null}{error ? <p className="mt-4 text-sm text-rose-200">{error}</p> : null}<button type="button" disabled={saving || !settings.open} onClick={onRestart} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-300 px-5 py-3 text-sm font-medium text-[#071014] transition hover:bg-violet-200 disabled:cursor-not-allowed disabled:opacity-40"><RotateCcw className={`h-4 w-4 ${saving ? "animate-spin" : ""}`} />{saving ? "Préparation…" : "Créer une nouvelle candidature"}</button></motion.section></div>;
}
