"use client";

import { DiscordAvatar } from "@/components/actor-trace";
import { RECRUITMENT_STATUS_LABEL, type RecruitmentAnalysis, type RecruitmentStatus, type VoiceSlot } from "@/lib/recruitment";
import { CalendarPlus, CheckCircle2, ExternalLink, FolderOpen, Loader2, LockKeyhole, MessageSquareText, Plus, Power, RefreshCw, Send, Vote, X } from "lucide-react";
import { motion } from "framer-motion";
import { readApiResponse } from "@/lib/api-response";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Application = { id: string; user_id: string; discord_name: string; discord_avatar_url: string; first_name: string; age: number; unique_id: string; experience: string; motivation: string; availability: string; integration_availability: string; document_url: string; trame_summary: string; personal_introduction: string; legal_rp_experience: string; illegal_rp_experience: string; servers_visited: string; rp_storylines: string; gm_missions: string; rp_events: string; suggestions: string; why_gm: string; qualities: string; long_term_contribution: string; staff_experience: string; additional_information: string; status: RecruitmentStatus; analysis: RecruitmentAnalysis | null; candidate_message: string | null; voice_slots: VoiceSlot[]; selected_voice_slot_id: string | null; submitted_at: string };
type StaffVote = { id: string; application_id: string; voter_id: string; voter_name: string; decision: string; comment: string };
type ApplicationHistory = { id: string; user_id: string; attempt_number: number; final_status: string; closed_from_status: string | null; candidate_message: string | null; votes_snapshot: StaffVote[]; archived_at: string };
type RecruitmentSettings = { open: boolean; message: string };
const VOTE_LABELS: Record<string, string> = { FAVORABLE: "Favorable", CONDITIONAL: "Sous conditions", MORE_INFO: "Informations nécessaires", UNFAVORABLE: "Défavorable", ABSTAIN: "Abstention" };

export function StaffRecruitmentPanel() {
  const [apps, setApps] = useState<Application[]>([]), [votes, setVotes] = useState<StaffVote[]>([]), [history, setHistory] = useState<ApplicationHistory[]>([]), [actorId, setActorId] = useState("");
  const [selectedId, setSelectedId] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [settings, setSettings] = useState<RecruitmentSettings>({ open: true, message: "" }), [settingsBusy, setSettingsBusy] = useState(false);
  const [settingsDirty, setSettingsDirty] = useState(false);
  const lastSyncRef = useRef<string | null>(null);
  const selected = apps.find((app) => app.id === selectedId) || apps[0];
  const selectedVotes = useMemo(() => votes.filter((vote) => vote.application_id === selected?.id), [votes, selected]);
  const selectedHistory = useMemo(() => history.filter((entry) => entry.user_id === selected?.user_id), [history, selected]);

  const refresh = useCallback(async (delta = false) => { if (!delta) setLoading(true); try { const since = delta && lastSyncRef.current ? `?since=${encodeURIComponent(lastSyncRef.current)}` : ""; const requests: Promise<Response>[] = [fetch(`/api/recruitment/staff${since}`, { cache: "no-store" })]; if (!delta) requests.push(fetch("/api/recruitment/settings", { cache: "no-store" })); const responses = await Promise.all(requests); const response = responses[0]; const result = await readApiResponse<{ applications: Application[]; votes: StaffVote[]; history: ApplicationHistory[]; actorId: string; syncAt: string; error: string }>(response); if (!response.ok) throw new Error(result.error || "Impossible de charger les candidatures."); const merge = <T extends { id: string }>(current: T[], incoming: T[]) => { const map = new Map(current.map((row) => [row.id, row])); for (const row of incoming) map.set(row.id, row); return [...map.values()]; }; if (delta) { setApps((current) => merge(current, result.applications || [])); setVotes((current) => merge(current, result.votes || [])); setHistory((current) => merge(current, result.history || [])); } else { setApps(result.applications || []); setVotes(result.votes || []); setHistory(result.history || []); const settingsResponse = responses[1]; const settingsResult = settingsResponse ? await readApiResponse<{ settings: RecruitmentSettings }>(settingsResponse) : null; if (settingsResponse?.ok && settingsResult?.settings) setSettings(settingsResult.settings); } lastSyncRef.current = result.syncAt || new Date().toISOString(); setActorId(result.actorId || ""); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger les candidatures."); } finally { if (!delta) setLoading(false); } }, []);
  useEffect(() => {
    const initial = window.setTimeout(() => void refresh(), 0);
    const timer = window.setInterval(() => { if (document.visibilityState === "visible") void refresh(true); }, 60000);
    const onVisible = () => { if (document.visibilityState === "visible") void refresh(true); };
    document.addEventListener("visibilitychange", onVisible);
    return () => { window.clearTimeout(initial); window.clearInterval(timer); document.removeEventListener("visibilitychange", onVisible); };
  }, [refresh]);

  async function update(body: Record<string, unknown>) { if (!selected) return false; setBusy(true); try { const response = await fetch(`/api/recruitment/staff/${selected.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await readApiResponse<{ application: Application; error: string }>(response); if (!response.ok || !result.application) throw new Error(result.error || "Mise à jour impossible."); setApps((list) => list.map((app) => app.id === selected.id ? result.application! : app)); setError(""); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Mise à jour impossible."); return false; } finally { setBusy(false); } }
  async function vote(decision: string, comment: string) { if (!selected) return false; setBusy(true); try { const response = await fetch(`/api/recruitment/staff/${selected.id}/vote`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, comment }) }); const result = await readApiResponse<{ vote: StaffVote; applicationStatus: RecruitmentStatus; error: string }>(response); if (!response.ok || !result.vote) throw new Error(result.error || "Vote impossible."); setVotes((list) => [...list.filter((v) => !(v.application_id === selected.id && v.voter_id === actorId)), result.vote!]); if (result.applicationStatus) setApps((list) => list.map((app) => app.id === selected.id ? { ...app, status: result.applicationStatus! } : app)); setError(""); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Vote impossible."); return false; } finally { setBusy(false); } }
  async function saveSettings(open: boolean) { setSettingsBusy(true); setError(""); try { const response = await fetch("/api/recruitment/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ open, message: settings.message }) }); const result = await readApiResponse<{ settings: RecruitmentSettings; error: string }>(response); if (!response.ok || !result.settings) throw new Error(result.error || "Modification impossible."); setSettings(result.settings); setSettingsDirty(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "Modification impossible."); } finally { setSettingsBusy(false); } }

  if (loading) return <div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="animate-spin text-violet-300" /></div>;
  return <main className="lab-bg relative min-h-dvh overflow-hidden p-6 text-white lg:p-10"><div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute top-0 left-1/4 h-72 w-72 rounded-full bg-violet-500/10 blur-[120px]" /><div className="absolute right-1/5 bottom-0 h-64 w-64 rounded-full bg-teal-500/8 blur-[110px]" /></div><div className="relative z-10 mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-white/35">Équipe référente</p><h1 className="mt-2 bg-gradient-to-r from-white/95 to-white/40 bg-clip-text text-3xl font-medium tracking-tight text-transparent">Recrutement GameMaster</h1><p className="mt-2 text-sm text-white/40">Analyse indicative, votes privés et organisation des vocaux.</p></div><div className="flex items-center gap-2"><button disabled={settingsBusy} onClick={() => void saveSettings(!settings.open)} title={settings.open ? "Fermer les recrutements" : "Ouvrir les recrutements"} className="inline-flex items-center gap-2 rounded-lg border border-white/[0.08] bg-white/[0.025] px-3 py-2 text-xs text-white/40 transition hover:bg-white/[0.055] hover:text-white/70 disabled:opacity-50"><span className={`h-1.5 w-1.5 rounded-full ${settings.open ? "bg-emerald-300/70" : "bg-white/25"}`}/><Power className="h-3.5 w-3.5"/>{settingsBusy ? "Modification…" : settings.open ? "Ouvert" : "Fermé"}</button><button aria-label="Actualiser les candidatures" onClick={() => void refresh()} className="rounded-lg border border-white/[0.08] bg-white/[.02] p-2 text-white/35 hover:bg-white/5 hover:text-white/65"><RefreshCw className="h-3.5 w-3.5" /></button></div></header>
    {!settings.open ? <details className="rounded-xl border border-white/[0.07] bg-white/[0.018] px-4 py-3"><summary className="cursor-pointer text-xs text-white/45">Message affiché pendant la fermeture</summary><textarea value={settings.message} onChange={(event) => { setSettings((current) => ({ ...current, message: event.target.value })); setSettingsDirty(true); }} rows={2} placeholder="Message affiché aux candidats…" className="mt-3 w-full resize-none rounded-lg border border-white/[0.07] bg-black/20 px-3 py-2 text-xs leading-5 text-white/55 outline-none"/>{settingsDirty ? <div className="mt-2 text-right"><button disabled={settingsBusy} onClick={() => void saveSettings(settings.open)} className="rounded-lg bg-white/10 px-3 py-1.5 text-xs text-white/65 hover:bg-white/15">Enregistrer</button></div> : null}</details> : null}
    {error && <div className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.07] p-4"><p className="text-sm font-medium text-amber-100">Candidatures indisponibles</p><p className="mt-1 text-xs leading-5 text-amber-100/60">{error}</p></div>}
    <div className="grid gap-5 lg:grid-cols-[300px_1fr]">
      <aside className="space-y-2">{apps.length ? apps.map((app) => { const attempts = history.filter((entry) => entry.user_id === app.user_id).length; return <button key={app.id} onClick={() => setSelectedId(app.id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition-colors ${selected?.id === app.id ? "border-violet-400/25 bg-violet-400/[0.07]" : "border-white/10 bg-white/[0.025] hover:bg-white/5"}`}><DiscordAvatar name={app.discord_name} url={app.discord_avatar_url} size={42} className="rounded-xl" /><span className="min-w-0 flex-1"><span className="block truncate font-medium">{app.first_name || app.discord_name}</span><span className="mt-1 flex items-center gap-2 text-xs text-white/40"><StatusDot status={app.status} />{RECRUITMENT_STATUS_LABEL[app.status]}</span>{attempts ? <span className="mt-1 block text-[10px] font-medium text-amber-200/65">Déjà candidat · {attempts} ancien{attempts > 1 ? "s" : ""} dossier{attempts > 1 ? "s" : ""}</span> : null}</span></button>; }) : !error ? <p className="rounded-2xl border border-white/10 p-5 text-sm text-white/40">Aucune candidature envoyée.</p> : null}</aside>
      {selected && <section className="space-y-5">
        {selectedHistory.length ? <PreviousApplicationsAlert entries={selectedHistory} /> : null}
        <div className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><DiscordAvatar name={selected.discord_name} url={selected.discord_avatar_url} size={58} className="rounded-2xl border-violet-300/20" /><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[11px] text-white/55"><StatusDot status={selected.status} />{RECRUITMENT_STATUS_LABEL[selected.status]}</div><h2 className="text-2xl font-medium">{selected.first_name} <span className="text-white/35">· {selected.discord_name}</span></h2><p className="mt-1 text-sm text-white/45">{selected.age} ans · ID {selected.unique_id}</p></div></div><a href={selected.document_url} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-400/[0.05] px-3 py-2 text-sm text-violet-100/75 hover:bg-violet-400/10"><FolderOpen className="h-4 w-4" />Ouvrir le dossier <ExternalLink className="h-3.5 w-3.5" /></a></div>
          <div className="mt-6 space-y-6"><StaffDetailGroup title="Présentation"><Text title="ID Discord" value={selected.user_id} compact/><Text title="Présentation personnelle" value={selected.personal_introduction} /></StaffDetailGroup><StaffDetailGroup title="Expériences RP"><Text title="Expérience légale" value={selected.legal_rp_experience || selected.experience} /><Text title="Expérience illégale" value={selected.illegal_rp_experience} /><Text title="Serveurs fréquentés" value={selected.servers_visited} /></StaffDetailGroup><StaffDetailGroup title="Vos idées"><Text title="Trames RP" value={selected.rp_storylines || selected.trame_summary} /><Text title="Missions GM" value={selected.gm_missions} /><Text title="Événements RP" value={selected.rp_events} /><Text title="Suggestions" value={selected.suggestions} /></StaffDetailGroup><StaffDetailGroup title="Pourquoi toi ?"><Text title="Pourquoi devenir GM" value={selected.why_gm || selected.motivation} /><Text title="Qualités" value={selected.qualities} /><Text title="Apport à long terme" value={selected.long_term_contribution} /></StaffDetailGroup><StaffDetailGroup title="Informations complémentaires"><Text title="Disponibilités" value={selected.availability} /><Text title="Expérience staff" value={selected.staff_experience} /><Text title="Autres informations" value={selected.additional_information} />{selected.integration_availability ? <Text title="Disponibilités pour l’intégration" value={selected.integration_availability} /> : null}</StaffDetailGroup></div>
        </div>
        {selected.analysis && <div className="grid gap-4 rounded-3xl border border-cyan-400/15 bg-cyan-400/[0.035] p-6 md:grid-cols-3"><List title="Points forts" items={selected.analysis.strengths} /><List title="Points à vérifier" items={selected.analysis.concerns} /><List title="Questions suggérées" items={selected.analysis.questions} /><p className="md:col-span-3 text-xs text-white/35">Avis automatique : {selected.analysis.recommendation}. {selected.analysis.documentAccessible ? "Le Google Docs public a été lu." : "Le document externe n’a pas pu être lu : l’avis repose sur les réponses du formulaire."} Cet avis ne décide jamais à la place du staff.</p></div>}
<StaffActions key={`${selected.id}:${selected.status}:${selected.candidate_message || ""}`} app={selected} votes={selectedVotes} actorId={actorId} busy={busy} onUpdate={update} onVote={vote} />
      </section>}
    </div>
  </div></main>;
}

function PreviousApplicationsAlert({ entries }: { entries: ApplicationHistory[] }) {
  return <section className="rounded-2xl border border-amber-400/25 bg-amber-400/[0.07] p-5"><div className="flex items-start gap-3"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-amber-300 shadow-[0_0_14px_rgba(252,211,77,.7)]"/><div className="min-w-0 flex-1"><h2 className="font-medium text-amber-100">Attention : ce candidat a déjà postulé</h2><p className="mt-1 text-xs leading-5 text-amber-100/55">{entries.length} ancienne{entries.length > 1 ? "s" : ""} candidature{entries.length > 1 ? "s" : ""} conservée{entries.length > 1 ? "s" : ""}. Consulte les décisions et motifs avant de voter.</p><div className="mt-4 space-y-2">{entries.map((entry) => { const previousStatus = entry.closed_from_status || entry.final_status; const voteReasons = (entry.votes_snapshot || []).filter((vote) => vote.comment); return <details key={entry.id} className="rounded-xl border border-amber-300/10 bg-black/20 p-3"><summary className="cursor-pointer text-sm text-white/70">Passage n°{entry.attempt_number} · {RECRUITMENT_STATUS_LABEL[previousStatus as RecruitmentStatus] || previousStatus} · {new Date(entry.archived_at).toLocaleDateString("fr-FR")}</summary><div className="mt-3 space-y-2 text-xs leading-5 text-white/50">{entry.candidate_message ? <p><b className="text-white/65">Motif communiqué :</b> {entry.candidate_message}</p> : <p>Aucun motif communiqué au candidat.</p>}{voteReasons.map((vote) => <p key={vote.id} className="rounded-lg bg-white/[0.04] p-2"><b className="text-white/65">{vote.voter_name}</b> · {VOTE_LABELS[vote.decision] || vote.decision} · {vote.comment}</p>)}</div></details>; })}</div></div></div></section>;
}

function StaffActions({ app, votes, actorId, busy, onUpdate, onVote }: { app: Application; votes: StaffVote[]; actorId: string; busy: boolean; onUpdate: (body: Record<string, unknown>) => Promise<boolean>; onVote: (decision: string, comment: string) => Promise<boolean> }) {
  type Action = "" | "MESSAGE" | "VOTE" | "VOICE" | "MORE_INFO" | "ACCEPT" | "REJECT" | "CLOSE";
  const [action, setAction] = useState<Action>(""), [message, setMessage] = useState(app.candidate_message || ""), [decision, setDecision] = useState("FAVORABLE"), [comment, setComment] = useState("");
  const [slots, setSlots] = useState<VoiceSlot[]>(app.voice_slots || []);

  function defaultMessage(next: Action) { if (next === "MORE_INFO") return "Nous avons besoin de quelques informations supplémentaires avant de poursuivre l’étude de ta candidature."; if (next === "ACCEPT") return "Félicitations, ta candidature est acceptée ! Merci de nous transmettre tes nouvelles disponibilités afin d’organiser ton intégration et ton start GameMaster."; if (next === "REJECT") return "Après étude de ta candidature, nous ne pouvons malheureusement pas donner une suite favorable pour le moment."; if (next === "CLOSE") return "Ta candidature est maintenant fermée. Merci pour le temps accordé au processus de recrutement."; if (next === "VOICE") return "Ton dossier a retenu notre attention. Nous souhaitons te proposer un entretien vocal."; return app.candidate_message || ""; }
  function selectAction(next: Action) { setAction(next); setMessage(defaultMessage(next)); if (next === "VOICE" && !slots.length) setSlots([{ id: crypto.randomUUID(), startsAt: "", note: "" }]); }
  async function confirm() { let success = false; if (action === "VOTE") success = await onVote(decision, comment); else if (action === "VOICE") success = await onUpdate({ status: "VOICE_PROPOSED", voiceSlots: slots, candidateMessage: message }); else if (action === "MORE_INFO") success = await onUpdate({ status: "MORE_INFO", candidateMessage: message }); else if (action === "ACCEPT") success = await onUpdate({ status: "ACCEPTED", candidateMessage: message }); else if (action === "REJECT") success = await onUpdate({ status: "REJECTED", candidateMessage: message }); else if (action === "CLOSE") success = await onUpdate({ status: "CLOSED", candidateMessage: message }); else if (action === "MESSAGE") success = await onUpdate({ candidateMessage: message }); if (success) setAction(""); }
  const needsMessage = ["MESSAGE", "VOICE", "MORE_INFO", "ACCEPT", "REJECT", "CLOSE"].includes(action);
  const disabled = busy || !action || (needsMessage && !message.trim()) || (action === "VOICE" && (!slots.length || slots.some((slot) => !slot.startsAt))) || (action === "VOTE" && ["CONDITIONAL", "MORE_INFO", "UNFAVORABLE"].includes(decision) && !comment.trim());
  const final = ["ACCEPTED", "REJECTED", "CLOSED"].includes(app.status), myVote = votes.find((vote) => vote.voter_id === actorId);
  const tally = Object.entries(VOTE_LABELS).map(([id, label]) => ({ id, label, count: votes.filter((vote) => vote.decision === id).length })).filter((row) => row.count);
  return <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-5 sm:p-6"><div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/[0.06] bg-black/15 p-3"><p className="text-[10px] uppercase tracking-wider text-white/25">Participation</p><p className="mt-1 text-lg font-medium">{votes.length} vote{votes.length > 1 ? "s" : ""}</p></div><div className="rounded-xl border border-white/[0.06] bg-black/15 p-3 sm:col-span-2"><p className="text-[10px] uppercase tracking-wider text-white/25">Tendance actuelle</p><p className="mt-1 text-sm text-white/65">{tally.length ? tally.map((row) => `${row.label} : ${row.count}`).join(" · ") : "Aucun vote enregistré"}</p></div></div><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-white/30">Gestion de la candidature</p><h3 className="mt-1 font-medium text-white/90">{final ? "Cette candidature est terminée" : "Que souhaites-tu faire ?"}</h3>{myVote ? <p className="mt-1 text-xs text-violet-200/45">Ton vote actuel : {VOTE_LABELS[myVote.decision] || myVote.decision}</p> : null}</div><select value={action} onChange={(event) => selectAction(event.target.value as Action)} className="min-w-[240px] rounded-xl border border-white/10 bg-[#111] p-3 text-sm text-white/75"><option value="">Choisir une action…</option><option value="MESSAGE">Envoyer un message</option>{!final ? <><option value="VOTE">{myVote ? "Modifier mon vote" : "Enregistrer mon vote"}</option><option value="MORE_INFO">Demander des informations</option><option value="VOICE">Proposer un entretien vocal</option><option value="ACCEPT">Accepter la candidature</option><option value="REJECT">Refuser la candidature</option></> : null}{app.status !== "CLOSED" ? <option value="CLOSE">Fermer la candidature</option> : null}</select></div>
    {action ? <motion.div key={action} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="mt-5 border-t border-white/[0.07] pt-5">
      {action === "VOTE" ? <div className="grid gap-3 sm:grid-cols-2"><select value={decision} onChange={(e) => setDecision(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 p-3 text-sm"><option value="FAVORABLE">Favorable</option><option value="CONDITIONAL">Favorable sous conditions</option><option value="MORE_INFO">Besoin d’informations</option><option value="UNFAVORABLE">Défavorable</option><option value="ABSTAIN">Abstention</option></select><textarea value={comment} onChange={(e) => setComment(e.target.value)} rows={3} placeholder="Justification privée…" className="rounded-xl border border-white/10 bg-black/30 p-3 text-sm outline-none sm:row-span-2" /></div> : null}
      {action === "VOICE" ? <div><div className="space-y-2">{slots.map((slot, index) => <div key={slot.id} className="flex items-center gap-2 rounded-xl border border-white/[0.07] bg-black/15 p-2"><CalendarPlus className="ml-1 h-4 w-4 text-violet-200/60" /><input type="datetime-local" value={slot.startsAt.slice(0,16)} onChange={(e) => setSlots((all) => all.map((item, itemIndex) => itemIndex === index ? { ...item, startsAt: e.target.value } : item))} className="min-w-0 flex-1 bg-transparent p-2 text-sm outline-none" /><button type="button" onClick={() => setSlots((all) => all.filter((_, itemIndex) => itemIndex !== index))} className="rounded-lg p-2 text-white/30 hover:bg-white/5 hover:text-white/70"><X className="h-4 w-4" /></button></div>)}</div>{slots.length < 3 ? <button type="button" onClick={() => setSlots((all) => [...all, { id: crypto.randomUUID(), startsAt: "", note: "" }])} className="mt-2 inline-flex items-center gap-1.5 text-xs text-violet-200/65"><Plus className="h-3.5 w-3.5" />Ajouter un autre créneau</button> : null}</div> : null}
      {needsMessage ? <textarea value={message} onChange={(e) => setMessage(e.target.value)} rows={action === "MESSAGE" ? 5 : 4} placeholder="Message visible par le candidat…" className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-sm leading-6 outline-none" /> : null}
      <div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-white/30">Le candidat verra immédiatement le nouveau message et son statut.</p><button disabled={disabled} onClick={() => void confirm()} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium disabled:opacity-40 ${action === "CLOSE" || action === "REJECT" ? "bg-rose-400/90 text-[#18090c]" : "bg-violet-300 text-[#071014]"}`}>{action === "VOTE" ? <Vote className="h-4 w-4" /> : action === "ACCEPT" ? <CheckCircle2 className="h-4 w-4" /> : action === "CLOSE" ? <LockKeyhole className="h-4 w-4" /> : action === "MESSAGE" || action === "MORE_INFO" ? <MessageSquareText className="h-4 w-4" /> : <Send className="h-4 w-4" />}{busy ? "Enregistrement…" : "Confirmer"}</button></div>
    </motion.div> : null}
    {app.selected_voice_slot_id ? <p className="mt-5 rounded-xl border border-emerald-400/15 bg-emerald-400/[0.05] p-3 text-sm text-emerald-200">Entretien choisi : {new Date(slots.find((slot) => slot.id === app.selected_voice_slot_id)?.startsAt || "").toLocaleString("fr-FR")}</p> : null}
    {votes.length ? <details className="mt-5 border-t border-white/[0.07] pt-4"><summary className="cursor-pointer text-xs text-white/40">Voir les votes enregistrés ({votes.length})</summary><div className="mt-3 space-y-2">{votes.map((vote) => <p key={vote.id} className="rounded-lg bg-white/[0.04] p-2 text-xs text-white/50"><b className="text-white/70">{vote.voter_name}</b> · {VOTE_LABELS[vote.decision] || vote.decision}{vote.comment ? ` · ${vote.comment}` : ""}</p>)}</div></details> : null}
  </section>;
}
function StatusDot({ status }: { status: RecruitmentStatus }) { const final = status === "ACCEPTED" || status === "REJECTED" || status === "CLOSED"; return <span className="relative flex h-2 w-2"><motion.span className={`absolute inline-flex h-full w-full rounded-full ${status === "ACCEPTED" ? "bg-emerald-300" : final ? "bg-white/30" : "bg-violet-300"}`} animate={final ? undefined : { scale: [1, 1.9, 1], opacity: [.8, .15, .8] }} transition={{ duration: 1.8, repeat: Infinity }} /><span className={`relative inline-flex h-2 w-2 rounded-full ${status === "ACCEPTED" ? "bg-emerald-300" : final ? "bg-white/40" : "bg-violet-300"}`} /></span>; }
function Text({ title, value, compact = false }: { title: string; value: string; compact?: boolean }) { return <div className={`min-w-0 overflow-hidden rounded-xl border border-white/[0.06] bg-black/15 p-4 ${compact ? "self-start" : ""}`}><p className="text-xs uppercase tracking-wider text-white/30">{title}</p><p className="mt-2 min-w-0 whitespace-pre-wrap break-words text-sm leading-6 text-white/65 [overflow-wrap:anywhere]">{value || "Non renseigné"}</p></div>; }
function StaffDetailGroup({ title, children }: { title: string; children: React.ReactNode }) { return <div><p className="mb-3 text-xs font-medium uppercase tracking-[.16em] text-violet-200/45">{title}</p><div className="grid gap-3 md:grid-cols-2">{children}</div></div>; }
function List({ title, items }: { title: string; items: string[] }) { return <div className="min-w-0 overflow-hidden"><p className="text-sm font-medium text-white/75">{title}</p><ul className="mt-3 space-y-2 break-words text-xs leading-5 text-white/50 [overflow-wrap:anywhere]">{items.map((item) => <li key={item}>• {item}</li>)}</ul></div>; }
